version: "3"

services:
  web:
    build: docker
    networks:
      - api
    depends_on:
      - db
    volumes:
      - "./:/app"
    ports:
      - 8100:80

  db:
    image: mariadb:10.1
    networks:
      - api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    ports:
      - 9906:3306

networks:
  api:
