#!/bin/bash

# Define variables
PHP_CS_FIXER="./sbin/php-cs-fixer.sh"
PHP_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [[ -n "$PHP_FILES" ]]; then
    # Run PHP-CS-Fixer
    ${PHP_CS_FIXER} ${PHP_FILES}

    # Build documentation
    echo "${PHP_FILES[@]}" | ./sbin/generate_documentation.sh
    git add docs/php
fi
