#!/bin/bash

# Define variables
PHP_CS_FIXER="./sbin/php-cs-fixer.sh"
PHP_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

# Run PHP-CS-Fixer
if [[ -n "$PHP_FILES" ]]; then
    ${PHP_CS_FIXER} ${PHP_FILES}
fi
